### ISSUE TITLE
Lazy loading of value not supported

### ISSUE THREAD

**Issue by bimal72** [markashleybell/mab.jquery.taginput#15]
Hi,
I am using Angular2 and created directive. Now my input value loads lazily.
How to populate existing lazily loaded values?

**Comment by markashleybell** [comment]
Hi, 

This plugin is only responsible for the behaviour and presentation of the tag input; the actual loading of suggestion data is performed by the Bloodhound suggestion engine built into [typeahead.js](https://github.com/twitter/typeahead.js).  

Lazy loading isn't something I've ever implemented, but as a starting point I'd suggest you take a look at the [docs for Bloodhound](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md), in particular the [remote](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote) options.
