### ISSUE TITLE
Contains instead of StartWith

### ISSUE THREAD

**Issue by jeansantos** [markashleybell/mab.jquery.taginput#17]
It is possible to have a contains filter instead of startwith?

**Comment by markashleybell** [comment]
I assume you mean for the autocompletion, i.e. matching substrings anywhere in the data as opposed to just the start?

All the typeahead functions are provided by [typeahead.js](https://twitter.github.io/typeahead.js/). It does look like this is possible, it just depends on you setting up your dataset correctly; see the first example here:

https://twitter.github.io/typeahead.js/examples/
